### PR TITLE
Make script compatible with Python 3 as well as Python 2.

### PR DESCRIPTION
**Pull request by grantps**
Only three minor changes and the script runs in Python 3 as well as in Python 2.

### CODE REVIEW

**Comment by fogonwater** [comment]
Awesome! Thanks, Grant! I'll review over the weekend and merge in.

**Comment by fogonwater** [comment]
Completely blanked on this. Merged now. Thanks heaps!

**Comment by grantps** [comment]
Slightly off-topic but have you considered giving a talk on your work in this area to the Python community? E.g. a Python conference or meet-up?

**Comment by fogonwater** [comment]
I hadn't really. I'm actually using Python on a large visualisation / publication project—both for data wrangling but also to manage the workflows. It won't finish until early next year, but it might be something that the community is interested in.

**Comment by grantps** [comment]
It sounds interesting and probably worth a conference presentation. Which city are you nearest to? The conference moves around and is bound to be nearby at some point.

**Pull request merged**
