### PR TITLE
Use Make for build, add tests, setup scripts and requirements.txt for pip. Fix some pep8 and pep257 warnings.

### PR DESCRIPTION
**Pull request by kinow**
Hello,

Thanks for sharing this. This pull request adds a Makefile for building the project. It doesn't work with Windows as it displays a usage menu using sed (never tried with Cygwin though).

There are some basic tests now, you can try with ./setup.py nosetests or make test.

The setup script uses setuptools and provides package information and nosetests.

There is also a requirements.txt shamelessly copied from the DPyLA project.

You can run pep8 and pep257 analysis as well. While writing this pull request I've fixed a few minor warnings. 

The only change in the Python code of the API, was to handle when the DNZ API returns errors. I got an error due to an invalid API (which happens when you select the text form your user profile screen and CTRL + V into the editor) but it wasn't clear what the error was about.

### CODE REVIEW

**Comment by fogonwater** [comment]
Great. Thanks Bruno. I'll check this out as soon as I can. You're a champ.

**Comment by kinow** [comment]
Awesome Chris. I was undecided on whether to send many smaller pull requests or a single on, so feel free to comment on specific parts if necessary (I can probably update the PR) or simply ignore the PR and manually merge anything you may find useful :)

**Comment by fogonwater** [comment]
Great. Tested and merged this into master. Thanks so much, Bruno!

**Comment by kinow** [comment]
Thank you for creating and sharing pydnz :)

**Comment by fogonwater** [comment]
Thanks for motivating me to do something more with it. When I get a little time, I'll tidy a few things I've notice, make it 2.x/3.x universal (it's nearly there) and contribute to pypy for `pip` installation. Thanks again, Bruno!

**Comment by kinow** [comment]
Awesome! Looking forward to a new version of pydnz. If you file some issues for what you have in mind for the next release I can take a look when I have some spare time and try to help too :)

**Pull request merged**
